from pathlib import Path

ROOT_DIR = Path(__file__).parent

VISUALS_DIR = ROOT_DIR/"Visuals"


SCREENS_DIR = VISUALS_DIR/"Screens"
CUTSCENES_DIR = SCREENS_DIR/"cutscenes"
CUTSCENE_VID_DIR = CUTSCENES_DIR/"videos"
IMAGES_DIR = SCREENS_DIR/"images"
MENUS_DIR = SCREENS_DIR/"menus"

SPRITES_DIR = VISUALS_DIR/"Sprites"
ENV_SPRITE_DIR = SPRITES_DIR/"environment"
OBJ_SPRITE_DIR = SPRITES_DIR/"objects"
PLAYER_SPRITE_DIR = SPRITES_DIR/"player"
